# Generated by Django 3.2.9 on 2021-11-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catergory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
