# Generated by Django 3.2.9 on 2021-11-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(max_length=150),
        ),
    ]
