# Generated by Django 3.2.9 on 2021-11-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
